### ISSUE TITLE
添加障碍物无效

### ISSUE THREAD

**Issue by yg1031** [wanghuohuo0716/hybrid_A_star#3]
![QQ截图20200507154202](https://user-images.githubusercontent.com/32894843/81267725-811faa00-9079-11ea-84d8-6e7c4ce72541.png)

**Comment by yg1031** [comment]
![QQ截图20200507154202](https://user-images.githubusercontent.com/32894843/81267882-c2b05500-9079-11ea-9aca-6901eeb59981.png)

**Comment by yg1031** [comment]
EntryPoint.m中添加的代码如下：
...
for i = 10:15
    ObstList(end+1,:) = [15, i];
end
...
tLine = [15, 10, 15, 15];
ObstLine(end+1,:) = tLine;
...

**Comment by wanghuohuo0716** [comment]
可能是代码中障碍物只是display了，并没有放在实际的检测计算中，可以看下VehicleCollisionCheck.m关于障碍物碰撞检测是如何检测的

**Comment by Van23Li** [comment]
VehicleCollisionCheck.m下的“obs_self_define=[-25, 30; 25, 30; 25, 5; 10, 5; 10, 0; -10, 0; -10, 5; -25, 5; -25, 30];”那一行需要换一下

**Comment by wanghuohuo0716** [comment]
> VehicleCollisionCheck.m下的“obs_self_define=[-25, 30; 25, 30; 25, 5; 10, 5; 10, 0; -10, 0; -10, 5; -25, 5; -25, 30];”那一行需要换一下


> EntryPoint.m中添加的代码如下： ... for i = 10:15 ObstList(end+1,:) = [15, i]; end ... tLine = [15, 10, 15, 15]; ObstLine(end+1,:) = tLine; ...


是的，添加自定义障碍物，需要添加显示障碍物的代码（simulator）和实际碰撞检查的代码，2个地方均需要修改
